# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_date_to',
            field=models.DateField(null=True),
        ),
    ]
