# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20180518_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user_on_trip',
            field=models.ManyToManyField(null=True, related_name='trips', to='login_app.User'),
        ),
    ]
